#! /bin/sh
# /etc/init.d/telebot
 
case "$1" in
  start)
    echo "Starting TelePi"
    # run application you want to start
    python /opt/TelePi/telebot.py &
    ;;
  stop)
    echo "Stopping TelePi"
    # kill application you want to stop
    killall python
    ;;
	restart)
    echo "Stopping TelePi"
    # kill application you want to stop
    killall python
    echo "Starting TelePi"
    python /opt/TelePi/telebot.py &
    ;;
  *)
    echo "Usage: /etc/init.d/TelePi{start|stop|restart}"
    exit 1
    ;;
esac
 
exit 0
